apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: savepoint-volume-claim
  namespace: workspace
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "local-path"
  volumeName: savepoint-volume
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-flink-volume-claim
  namespace: workspace
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "local-path"
  volumeName: shared-flink-volume
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: checkpoint-volume-claim
  namespace: workspace
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "local-path"
  volumeName: checkpoint-volume
  volumeMode: Filesystem
