apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: reactive-dev
  namespace: workspace
spec:
  image: "registry.internal.local/flink/flink-deployments:flink-main-container-custom"
  imagePullPolicy: Always
  flinkVersion: v1_19
  flinkConfiguration:
    # scheduler-mode: REACTIVE
    taskmanager.numberOfTaskSlots: "1"
    state.checkpoints.dir: file:///home/dev/checkpoints/
    state.savepoints.dir: file:///home/dev/savepoints/
    execution.checkpointing.interval: 10s
    env.java.opts: -XX:+UseG1GC -Xms100m -Xmx250m -XX:NativeMemoryTracking=summary
    job.autoscaler.enabled: "true"
    job.autoscaler.scaling.enabled : "true"
    job.autoscaler.stabilization.interval: 1m
    job.autoscaler.metrics.window: 2m
    job.autoscaler.target.utilization: "0.7"
    job.autoscaler.target.utilization.boundary: "0.2"
    job.autoscaler.restart.time: 2m
    job.autoscaler.catch-up.duration: 2m
    pipeline.max-parallelism: "5"
    jobmanager.scheduler: "adaptive"
    akka.client.timeout: "900000"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "1048m"
      cpu: 1
  taskManager:
    replicas: 2
    resource:
      memory: "2048m"
      cpu: 0.5
  podTemplate:
      spec:
        containers:
          - name: flink-main-container
            volumeMounts:
              - name: checkpoint-volume
                mountPath: /home/dev/checkpoints/
              - name: savepoint-volume
                mountPath: /home/dev/savepoints/
        volumes:
          - name: checkpoint-volume
            persistentVolumeClaim:
              claimName: checkpoint-volume-claim
          - name: savepoint-volume
            persistentVolumeClaim:
              claimName: savepoint-volume-claim
  restartNonce: {{ .Values.restartValue }}
  job:
    jarURI: "local:///opt/flink/app/jobs/flink_job.py"
    entryClass: "org.apache.flink.client.python.PythonDriver"
    args: ["-py", "/opt/flink/app/jobs/flink_job.py"]
    parallelism: 1
    
  
  # mode: standalone
