apiVersion: v1
kind: Service
metadata:
  name: traefik-metrics
  namespace: workspace
  labels:
    app: traefik
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8082"
spec:
  selector:
    app: traefik
  ports:
    - name: metrics
      port: 8082
      targetPort: metrics
  type: ClusterIP
