apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service
  namespace: workspace

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: web
      nodePort: 30000
  selector:
    app: traefik