kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-deployment
  namespace: workspace
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-account
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "CriticalAddonsOnly"
          operator: "Exists"
          effect: "NoExecute"
      containers:
        - name: traefik
          image: docker.io/library/traefik:v3.4.1
          env:
            - name: TARGET_NAMESPACE
              value: workspace
          args:
            - --entryPoints.web.address=:80
            - --api.insecure
            - --providers.kubernetesingress
            - --providers.kubernetescrd=true
            - --providers.kubernetescrd.allowCrossNamespace=true
            - --metrics.prometheus=true
            - --metrics.prometheus.entrypoint=metrics
            - --metrics.prometheus.addserviceslabels=true
            - --metrics.prometheus.addrouterslabels=true
            - --entryPoints.metrics.address=:8082
          ports:
            - name: web
              containerPort: 80
            - name: dashboard
              containerPort: 8080
            - name: metrics
              containerPort: 8082