apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  registries.conf: |
    registries:
      - name: Internal Registry
        prefix: registry.internal.local
        api_url: http://172.17.0.1:5000
        insecure: true