apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-manager
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-manager-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: helm-manager
    namespace: kube-system
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: helm-manager
  namespace: kube-system
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: helm-manager
          containers:
            - name: helm-manager
              image: registry.internal.local/tools/helm_manager:latest
              imagePullPolicy: Always
              env:
                - name: ARGOCD
                  value: "true"
                - name: KUBEOPSVIEW
                  value: "true"
              envFrom:
                - configMapRef:
                    name: proxy-config
              resources:
                requests:
                  cpu: 130m
                  memory: 130Mi
                limits:
                  cpu: 250m
                  memory: 256Mi
